language: node_js
node_js:
  - stable
  - 5
  - 4
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
after_success:
  # report coverage to coveralls
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  # report coverage to codecov.io
  - bash <(curl https://codecov.io/bash)
